/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.ImplementasiPCD;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class App {
    public static void main(String[] args) {
        
        // MEMBACA CITRA
        BufferedImage img = null;
        File f = null;
        try{
            File input = new File("E:\\FILE-KULIAH\\SEMESTER-7\\PCD\\ImplementasiPCD\\FotoTest1.png");
            img = ImageIO.read(input);
        }
        catch(IOException E) {
            System.out.println(E);
        }
        
        // MENDAPATKAN NILAI PIXEL
        int width = img.getWidth();
        int height = img.getHeight();
        
        for (int i = 0; i < height; i++) {
            for (int x = 0; x < width; x++) {
                Color c = new Color(img.getRGB(x, i));
                int r = c.getRed();
                int g = c.getGreen();
                int b = c.getBlue();
                int avg = (r + g + b) / 3;
                System.out.print(" " + avg);
            }
            System.out.println(" ");
        }
    }
}
