/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.pcd.Logika;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;

public class App {
        public static void main(String[] args)throws IOException {
        BufferedImage imgA = null,imgB = null;
           try{
              File input = new File("E:\\FILE-KULIAH\\SEMESTER-7\\PCD\\pcd_Logika\\bahan1.jpeg");
              imgA = ImageIO.read(input);
              input = new File("E:\\FILE-KULIAH\\SEMESTER-7\\PCD\\pcd_Logika\\bahan1.jpeg");
              imgB = ImageIO.read(input);
            }
        catch(IOException e){
             System.out.println(e);
             
        }
           int width = imgA.getWidth(); 	// mengambil nilai lebar gambarA
           int height = imgA.getHeight(); 	// mengambil nilai tinggi gambarA
           int r,g,b,avg;
           Color colorA,colorB;
           int matriksA[ ][ ] = new int[(width)][(height)]; // Array penempung
           int matriksB[ ][ ] = new int[(width)][(height)];
           for (int y = 0; y < height; y++) {
       for (int x = 0; x < width; x++) {
            colorA= new Color(imgA.getRGB(x,y)); // mengambil nilai pixel
            r = colorA.getRed();		// mengambil nilai merah
            g = colorA.getGreen(); 	// mengambil nilai hijau
            b = colorA.getBlue(); 	// mengambil nilai biru
            avg = (r+g+b)/3;    
            matriksA[x][y] = avg;
             colorB= new Color(imgB.getRGB(x,y)); // mengambil nilai pixel
            r = colorB.getRed();		// mengambil nilai merah
            g = colorB.getGreen(); 	// mengambil nilai hijau
            b = colorB.getBlue(); 	// mengambil nilai biru
            avg = (r+g+b)/3;    
            matriksB[x][y] = avg;
            
         }
       }
              int Operasi = 0 ;
                int na = 200; 
                int nb = 200;
                for (int y = 0; y < height; y++){
             for (int x = 0; x < width; x++){
                boolean hasil = ( na>=matriksA[x][y] ) && ( nb>matriksB[x][y] );
                if (hasil==true){
                    Operasi=255;
                }else {
                    Operasi=0;
                }
                System.out.print(" "+Operasi);
                Color avgBaru = new Color(Operasi,Operasi,Operasi);
                imgA.setRGB(x, y, avgBaru.getRGB());                 
              }

          System.out.println();
        }  
        File Output = new File("E:\\FILE-KULIAH\\SEMESTER-7\\PCD\\pcd_Logika\\output.jpg");
        ImageIO.write(imgA, "jpg", Output);
    }
}
